### ISSUE TITLE
[FEATURE] davrods on different host than yoda

### ISSUE THREAD

**Issue by mkorthof** [UtrechtUniversity/yoda-ansible#78]
#### Is your feature request related to a problem? Please describe.

Please add an option to install davrods to a different host/resource server.

#### Describe the solution you'd like

Adding davrods to inventory/host_vars so the role gets deployed to specified host.

#### Describe alternatives you've considered

Currently we're using a 'post deploy' playbook:

```
- name: Deploy davrods
  hosts: all
  become: yes
  roles:
    - apache
    - yoda_davrods
  tags:
    - davrods
``` 

#### Additional context
Ex. *Here's a photo of my cat!*
